export const data = [
  {
    label: "Hà Nội",
    options: [
      { value: "BaDinh", label: "Ba Đình" },
      { value: "HoanKiem", label: "Hoàn Kiếm" },
      { value: "DongDa", label: "Đống Đa" },
      { value: "HaiBaTrung", label: "Hai Bà Trưng" },
      { value: "CauGiay", label: "Cầu Giấy" },
      { value: "ThanhXuan", label: "Thanh Xuân" },
      { value: "HoangMai", label: "Hoàng Mai" },
      { value: "LongBien", label: "Long Biên" },
      { value: "NamTuLiem", label: "Nam Từ Liêm" },
      { value: "BacTuLiem", label: "Bắc Từ Liêm" },
      { value: "TayHo", label: "Tây Hồ" },
      { value: "HaDong", label: "Hà Đông" },
    ],
  },
  {
    label: "TP Hồ Chí Minh",
    options: [
      { value: "District1", label: "Quận 1" },
      { value: "District3", label: "Quận 3" },
      { value: "TanBinh", label: "Tân Bình" },
      { value: "PhuNhuan", label: "Phú Nhuận" },
      { value: "BinhThanh", label: "Bình Thạnh" },
      { value: "District7", label: "Quận 7" },
      { value: "GoVap", label: "Gò Vấp" },
      { value: "ThuDuc", label: "Thủ Đức" },
    ],
  },
];

export const wardsData = {
  BaDinh: [
    { value: "PhucXa", label: "Phúc Xá" },
    { value: "NguyenTrungTruc", label: "Nguyễn Trung Trực" },
    { value: "DienBien", label: "Điện Biên" },
    { value: "CongVi", label: "Cống Vị" },
    { value: "LieuGiai", label: "Liễu Giai" },
    { value: "NgocHa", label: "Ngọc Hà" },
    { value: "KimMa", label: "Kim Mã" },
    { value: "NgocKhanh", label: "Ngọc Khánh" },
    { value: "QuanThanh", label: "Quán Thánh" },
    { value: "ThanhCong", label: "Thành Công" },
  ],
  HoanKiem: [
    { value: "HangBac", label: "Hàng Bạc" },
    { value: "HangDao", label: "Hàng Đào" },
    { value: "CuaDong", label: "Cửa Đông" },
    { value: "DongXuan", label: "Đồng Xuân" },
    { value: "LyThaiTo", label: "Lý Thái Tổ" },
    { value: "TrangTien", label: "Tràng Tiền" },
    { value: "PhanChuTrinh", label: "Phan Chu Trinh" },
    { value: "HangGai", label: "Hàng Gai" },
    { value: "HangBong", label: "Hàng Bông" },
    { value: "HangMa", label: "Hàng Mã" },
    { value: "HangBuom", label: "Hàng Buồm" },
    { value: "HangBai", label: "Hàng Bài" },
  ],
  DongDa: [
    { value: "LangHa", label: "Láng Hạ" },
    { value: "CatLinh", label: "Cát Linh" },
    { value: "KhamThien", label: "Khâm Thiên" },
    { value: "TrungPhung", label: "Trung Phụng" },
    { value: "NamDong", label: "Nam Đồng" },
    { value: "OChoDua", label: "Ô Chợ Dừa" },
    { value: "QuocTuGiam", label: "Quốc Tử Giám" },
    { value: "VanChuong", label: "Văn Chương" },
    { value: "PhuongMai", label: "Phương Mai" },
    { value: "ThinhQuang", label: "Thịnh Quang" },
    { value: "LangThuong", label: "Láng Thượng" },
    { value: "TrungTu", label: "Trung Tự" },
  ],
  HaiBaTrung: [
    { value: "BachMai", label: "Bạch Mai" },
    { value: "QuynhMai", label: "Quỳnh Mai" },
    { value: "QuynhLoi", label: "Quỳnh Lôi" },
    { value: "MinhKhai", label: "Minh Khai" },
    { value: "ThanhNhi", label: "Thanh Nhàn" },
    { value: "DongNhon", label: "Đồng Nhân" },
    { value: "BachDang", label: "Bạch Đằng" },
    { value: "VinhTuy", label: "Vĩnh Tuy" },
    { value: "LeDaiHanh", label: "Lê Đại Hành" },
    { value: "PhoHue", label: "Phố Huế" },
    { value: "NguyenDu", label: "Nguyễn Du" },
  ],
  CauGiay: [
    { value: "QuanHoa", label: "Quan Hoa" },
    { value: "NghiaDo", label: "Nghĩa Đô" },
    { value: "NghiaTan", label: "Nghĩa Tân" },
    { value: "MaiDich", label: "Mai Dịch" },
    { value: "DichVong", label: "Dịch Vọng" },
    { value: "DichVongHau", label: "Dịch Vọng Hậu" },
    { value: "YenHoa", label: "Yên Hòa" },
    { value: "TrungHoa", label: "Trung Hòa" },
  ],
  ThanhXuan: [
    { value: "KhuongMai", label: "Khương Mai" },
    { value: "KhuongTrung", label: "Khương Trung" },
    { value: "ThanhXuanBac", label: "Thanh Xuân Bắc" },
    { value: "ThanhXuanNam", label: "Thanh Xuân Nam" },
    { value: "ThanhXuanTrung", label: "Thanh Xuân Trung" },
    { value: "PhuongLiet", label: "Phương Liệt" },
    { value: "HaDinh", label: "Hạ Đình" },
    { value: "NhanChinh", label: "Nhân Chính" },
  ],
  HoangMai: [
    { value: "GiapBat", label: "Giáp Bát" },
    { value: "HoangVanThu", label: "Hoàng Văn Thụ" },
    { value: "LinhNam", label: "Lĩnh Nam" },
    { value: "MaiDong", label: "Mai Động" },
    { value: "ThinhLiet", label: "Thịnh Liệt" },
    { value: "VinhHung", label: "Vĩnh Hưng" },
    { value: "YenSo", label: "Yên Sở" },
    { value: "DaiKim", label: "Đại Kim" },
  ],
  LongBien: [
    { value: "ThuongThanh", label: "Thượng Thanh" },
    { value: "NgocLam", label: "Ngọc Lâm" },
    { value: "NgocThuy", label: "Ngọc Thụy" },
    { value: "BoDe", label: "Bồ Đề" },
    { value: "VietHung", label: "Việt Hưng" },
    { value: "DucGiang", label: "Đức Giang" },
    { value: "GiaThuy", label: "Gia Thụy" },
  ],
};
